{
 "title": "Container analysis",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name != \"\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name != \"\"}[5m]) * 100) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Storage used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name!=\"\"} / container_fs_limit_bytes{name!=\"\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total storage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name!=\"\"} / 1000000000) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (cum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"} / 1000000000) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx kB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\"}[5m]) / 1000) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx kB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\"}[5m]) / 1000) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}